# Generated by Django 4.2.7 on 2025-06-19 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0002_booking_created_at_booking_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AddField(
            model_name='booking',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes for admin use only'),
        ),
        migrations.AddField(
            model_name='booking',
            name='admin_response',
            field=models.TextField(blank=True, help_text="Admin's response to this booking"),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
